# Generated by Django 4.1.4 on 2022-12-12 06:19

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('icon', versatileimagefield.fields.VersatileImageField(upload_to='icon/', verbose_name='Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=128)),
                ('customer_name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='customer email')),
                ('phone', models.CharField(max_length=128)),
                ('from_address', models.TextField()),
                ('to_address', models.TextField()),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('ORDER PROCESSING', 'ORDER PROCESSING'), ('SHIPMENT PENDING', 'SHIPMENT PENDING'), ('ESTIMATED DELIVERY', 'ESTIMATED DELIVERY')], default=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('comments', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.order')),
                ('order_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.icon')),
            ],
        ),
    ]
