# Generated by Django 4.1.4 on 2022-12-13 04:52

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_icon_order_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=225)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='testimonials/', verbose_name='Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('decription', models.CharField(max_length=500)),
            ],
        ),
    ]
