# Generated by Django 4.1.4 on 2022-12-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=25)),
                ('width', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cargo Request',
            },
        ),
    ]
