# Generated by Django 4.1.4 on 2022-12-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargorequest',
            name='from_country',
            field=models.CharField(choices=[('', '--select--'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('American Samoa', 'American Samoa'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antarctica', 'Antarctica'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Aruba', 'Aruba'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'), ('Bolivia', 'Bolivia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cargorequest',
            name='services',
            field=models.CharField(choices=[('', '--select--'), ('Air cargo', 'Air cargo'), ('Sea cargo', 'Sea cargo'), ('Port to port service', 'Port to port service'), ('Moving service', 'Moving service'), ('Express delivery', 'Express delivery')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cargorequest',
            name='to_country',
            field=models.CharField(choices=[('', '--select--'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran, Islamic Republic of', 'Iran, Islamic Republic of'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Korea, Republic of', 'Korea, Republic of'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cargorequest',
            name='weight',
            field=models.CharField(choices=[('', '--select--'), ('100Kg', '100Kg'), ('200Kg', '200Kg'), ('300Kg', '300Kg'), ('400Kg', '400Kg'), ('500Kg', '500Kg'), ('600Kg', '600Kg'), ('700Kg', '700Kg')], max_length=100),
        ),
    ]
